services:
  Esrefly:
    container_name: esrefly_ai
    image: esrefly_ai:latest
    build:
      context: .
    ports:
      - 5000:8080
    networks:
      - esrefly-ai-network
    env_file:
      - .env
    restart: on-failure
    depends_on: 
      - Ollama
      - SqlServer 
  
  SqlServer:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password123
    healthcheck: 
      test: ["NONE","/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "yourStrong(!)Password123","-C", "-Q", "SELECT 1"]
      interval: 15s
      timeout: 1m
      retries: 2
    volumes:
      - database-volume:/var/opt/mssql
    networks:
      - esrefly-ai-network
    restart: on-failure

  Ollama:
    container_name: ollama
    image: ollama/ollama
    ports:
      - 14343:14343
    volumes:
      - ./run.sh:/bin/run.sh
    networks:
      - esrefly-ai-network
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama serve &
        sleep 2
        ollama pull llama3.2:1b
        tail -f /dev/null
    restart: on-failure
    
    

networks:
  esrefly-ai-network:    
  
volumes:
  database-volume:    